### ISSUE TITLE
Can't override test job keybinding

### ISSUE THREAD

**Issue by cd-a** [Canop/bacon#116]
Hi,

I want to use `nextest` inside bacon, instead of the normal test.

For that I have defined the job in the global `prefs.toml` file. 

When I bind it to `n`, it works. 
However, binding it to `t` does not work, it keeps using the standard test. 

Am I missing something or is this not supported yet?

This works:
```toml

[keybindings]
n = "job:nextest"

[jobs.nextest]
command = ["cargo", "nextest", "run", "--color", "always"]
need_stdout = true
```

This does not work:
```toml

[keybindings]
t = "job:nextest"

[jobs.nextest]
command = ["cargo", "nextest", "run", "--color", "always"]
need_stdout = true
```

bacon 2.6.2

**Comment by Canop** [comment]
You're right: the way default keybindings works now isn't ideal. I'll change that.

In the meantime a workaround is to have a `bacon.toml` file in your repository, with this:

```TOML
[keybindings]
t = "job:nextest"
```
