### ISSUE TITLE
[Bug] A job that runs `cargo test -- --include-ignored` fails to work 

### ISSUE THREAD

**Issue by rszyma** [Canop/bacon#130]
I've defined a custom job called `test-all`:
```toml
[jobs.test-all]
command = ["cargo", "test", "--color", "always", "--", "--color", "always", "--include-ignored"]
need_stdout = true
```
The difference between this and default `test` job is that it uses `--include-ignored` flag to also run tests with `#[ignore]` attribute.

When I run this job and any of the tests fail this is the result:
![image](https://user-images.githubusercontent.com/44318430/231746548-134f0863-5e1b-473e-b15d-4c294cf40ba6.png)

There are 2 problems here:
1. I can't scroll the output.
2. It fails with `Command error code: 101`. I've skimmed through the code and figured out that `AppState.cmd_result` is `CommandResult::Failure`, so I the command output failed to parse maybe?
