### ISSUE TITLE
working with just

### ISSUE THREAD

**Issue by nim65s** [Canop/bacon#144]
Hello !

Thanks a lot for this project :D

I was wondering if there are ways to integrate bacon with [just](https://github.com/casey/just), or if something  is planned.

To provide more context, I often have to write a `justfile` with many commands, and bacon is a super nice tool to run some of those commands automatically, so I have to write a `bacon.toml` which just expose the list of the just command I need.

Here is an example on a toy project : [justfile](https://github.com/nim65s/RobotS/blob/main/.justfile) / [bacon.toml](https://github.com/nim65s/RobotS/blob/main/bacon.toml).

This is a bit of boilerplate that I have to write and adapt again and again in every project (and maintain), for very little added value, while I think we could instead have just a flag for bacon that expose commands provided by just.

**Comment by Canop** [comment]
There's nothing planned, because I never used `just` and nobody asked for it.

I guess there could be something specific done.

In the meantime, what about this:

```
[jobs.just]
command = ["just"]
need_stdout = false

```
You would call it like

`bacon just -- check-drv`

**Comment by nim65s** [comment]
Thanks for your answer !

This workaround would work, but it would opt me off  the `?` menu, and prevent me from declaring shortcuts, right ?
If this is the case, I think the workaround of just writing the boilerplate is preferable.

What I would ideally look for would probably more be like
```toml
[jobs-just]
commands  = ["check-drv", "check-esp", "clippy-drv", "clippy-esp"]

[keybindings]
t = "job-just:check-drv"
s = "job-just:check-esp"
shift-t = "job-just:clippy-drv"
shift-s = "job-just:clippy-esp"
```
or even a blunt `import_all_jobs_from_just = true`

(this `jobs-just` / `job-just` naming is awful, though)
