### ISSUE TITLE
[feature request] Expand env vars in job command

### ISSUE THREAD

**Issue by jalil-salame** [Canop/bacon#181]
I use env vars as arguments to my executable so I would like support for expanding them before being passed to the executable:

```toml
[jobs.run]
command = ["cargo", "run", "--", "$MY_VAR"]
```

`$MY_VAR` should be expanded before being passed to `cargo run`.
