### ISSUE TITLE
Synergy with cargo nextest

### ISSUE THREAD

**Issue by jacg** [Canop/bacon#196]
I find both `bacon` and [`cargo nextest`](https://nexte.st/) to be very useful, and I would like to use them together.

I can persuade `bacon` to run tests via `cargo nextest` by specifying this in `bacon.toml`:

```toml

[jobs.test]
command = [
    "cargo", "nextest", "run", "--color", "always",
]
need_stdout = true
```

When the tests pass I get to see nextest's highly-informative output (in colour, even though it doesn't show up here):
```

    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.01s
    Starting 1 test across 1 binary (run ID: f68cbdcf-7b7a-4af8-a5f6-01a0005a7d89, nextest profile: default)
        PASS [   0.003s] rust tests::it_works
------------
     Summary [   0.003s] 1 test run: 1 passed, 0 skipped
```

 but when the tests fail, I get the very unhelpful and disapponting

```
 1  failed: tests::it_is_broken
 no output
```
Can `bacon` be made to work with `cargo nextest`?
