### ISSUE TITLE
Bacon gets confused when the build command has unexpected output

### ISSUE THREAD

**Issue by jyn514** [Canop/bacon#24]
This is a screenshot of `bacon` after saving a modified file, after bacon starts up for the first time.

![image](https://user-images.githubusercontent.com/23638587/99345316-ff96a900-285f-11eb-91e5-80f56d588a25.png)

I would expect the extra output to be either hidden or shown with proper line wrapping, not with weird indentation.

You can reproduce by running bacon on `rustc` (rustc strikes again!) with the following `bacon.toml`:

```toml
default_job = "check"

[jobs]

[jobs.check]
command = ["x", "check", "--color", "always"]

[jobs.clippy]
command = ["x", "clippy", "--color", "always"]
```
