### ISSUE TITLE
Is there a way to keep bacon from capturing the output? 

### ISSUE THREAD

**Issue by matthewgapp** [Canop/bacon#250]
Hey thanks for this project! 

I'm thinking of migrating from cargo watch to bacon. But it's frustrating to run my server and navigate its log output via Bacon. I'd prefer that bacon simply output the raw logs from my server to my terminal so that I can use search and scroll functionality of my terminal to navigate the logs. 

Is this possible today?

**Comment by irh** [comment]
I'd also like the ability to turn off the analyzer for certain jobs. I was thinking something like:

```toml
[jobs.server]
command = ["..."]
need_stdout = true
analyzer = "none"
```
