### ISSUE TITLE
With miri errors are not highlighted

### ISSUE THREAD

**Issue by Ddystopia** [Canop/bacon#251]
Hello, which that conf added:

```toml
[jobs.miri]
command = ["cargo", "miri", "run", "--color", "always"]
need_stdout = true
```

bacon looks like this:

![image](https://github.com/user-attachments/assets/1734106d-6e2f-4356-9ff1-c63e1f5ab2c3)

This is output if command is run directly:

![image](https://github.com/user-attachments/assets/40b63e87-3108-49c5-bfec-502ed4be1fb7)
