### ISSUE TITLE
Orphaned process when using script

### ISSUE THREAD

**Issue by c-git** [Canop/bacon#287]
Hi,

I need to do cleanup before calling cargo run to test when the egui state is not available. (After run is also fine but seeing as how it will usually get killed I don't think that works). The problem I have is that if I call `cargo run` from a script the process gets orphaned when a change is detected and then a new one is started. 

Example script

```sh
echo "Doing cleanup..."
cargo run
```

Example bacon.toml

```toml
[jobs.run-with-cleanup]
command = [
  "sh",
  "-e",
  "./scripts/example.sh",
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
```
