### ISSUE TITLE
watch triggers outside folder

### ISSUE THREAD

**Issue by TN19N** [Canop/bacon#300]
when running bacon inside a member of workspace

```bash
cd ./crates/gateway
bacon run
```

with this config ./crates/gateway/bacon.toml
```toml
[jobs.run]
command = ["cargo", "run"]
need_stdout = true
background = false
on_change_strategy = "kill_then_restart"
apply_gitignore = false
watch = [".env"]
```

if i modified any other member of the workspace bacon run get reruns
for example editing: ./crates/users/main.rs

I expected to nor rerun or i am missing something ?

**Comment by Canop** [comment]
bacon watches the sources of all packages defined by the workspace.

You can change this either by

1. setting `default_watch = false` in the job and manually define what you want to watch with the `watch` property, or
2. launching bacon with `bacon run --watch .`

Does this work for you ? Feedback on this question welcome. I wonder whether we want a `watch_all_workspace_packages=false` config parameter (alternatively we may imagine that in most cases it would be enough to watch only the Cargo.toml files of other packages).

**Comment by TN19N** [comment]
I changed the configuration to:

```toml
[jobs.run]
command = ["cargo", "run"]
need_stdout = true
background = false
on_change_strategy = "kill_then_restart"
# apply_gitignore = false
default_watch = false
watch = ["."]
```

However, it still doesn't work as expected. The changes are detected outside the crate folder.
When I run it manually with --watch ., it works fine. Shouldn't this configuration achieve the same result?

Additional Note:
    If I uncomment the apply_gitignore line, running bacon run causes it to freeze.
