### ISSUE TITLE
Custom sounds

### ISSUE THREAD

**Issue by nc7s** [Canop/bacon#337]
Currently, we have some sounds hand picked by the authors baked into the compiled executable. It works, but has shortcomings. In Debian particularly, the included sound resources have too many copyright holders: even though they are OK license wise with CC0, we can't reliably attribute each to their respective author(s). I'll have to exclude them, and disable the sound feature for now. Allowing custom sounds won't solve the attribution problem, but does enable the feature.

Currently sounds are referred to by names, e.g. `on_success = "play-sound(name=90s-game-ui-6,volume=50)"`. Presumably we can also refer by paths, e.g. `play-sound(path=~/Audio/my-awesome-notification.mp3,volume=42)`.

We could also allow naming custom sounds, something like this:

```toml
# prefs.toml
[sound.collection]
my-awesome-notification = '~/Audio/my-awesome-notification.mp3'
```

```toml
# bacon.toml
[jobs.check]
on_success = 'play-sound(my-awesome-notification,volume=42)'
```
