### ISSUE TITLE
No output with jq in long running task

### ISSUE THREAD

**Issue by Spartan09** [Canop/bacon#345]
I am having some trouble prettifying json output inside `bacon`, these are my options:
```toml
[jobs.run-long]
command = ["sh", "-c", "cargo run | jq"]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
```
### This is what I want:

![Image](https://github.com/user-attachments/assets/47b07819-ee4c-4d8b-a433-bf8b77eeccf3)

### This is what I am getting inside bacon with `jq` formatter:
```toml
[jobs.run-long]
command = ["sh", "-c", "cargo run | jq"]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
```

![Image](https://github.com/user-attachments/assets/b84b5d50-a20f-4226-8b48-9a166c93404e)

### and this is what I am getting with `bunyan` formatter:
```toml
[jobs.run-long]
command = ["sh", "-c", "cargo run | bunyan"]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
```

![Image](https://github.com/user-attachments/assets/2393175d-652d-4369-bce3-64b41d8551c2)

Any ideas on how I can resolve this?

**Comment by Canop** [comment]
It's probably's just jq removing colors because it's not directly executed in a TTY.

This should work:

    command = ["sh", "-c", "cargo run | jq -C"]

**Comment by Spartan09** [comment]
Its showing no output like so:

![Image](https://github.com/user-attachments/assets/20a5be4d-5c48-42f5-90c5-8cf33970f3e4)

**Comment by Canop** [comment]
Ok, I found out that jq also doesn't flush its output..

This should work:

```
command = [
    "sh", "-c", "cargo run | jq -C --unbuffered"
]
```

**Comment by Spartan09** [comment]
but now the program keeps running in the background even after pressing `q`

**Comment by c-git** [comment]
It's quite possible it always was and you just weren't seeing any output. Although you might have got an error when you tried to restart the server the next time if you're always using the same port.

You need to include the kill command from the example here https://dystroy.org/bacon/cookbook/#bacon-cli-snippets

I think it's needed when the process that gets started spawns other processes

> kill = ["pkill", "-TERM", "-P"]'

**Comment by Canop** [comment]
It's up to you to know if your program needs some cleaning. But if there's no problem for TERM, it's supposed to be cleaner and more future-proof.

**Comment by Canop** [comment]
Renamed the issue to try make it easier to find for anybody having the same issue.

**Comment by Spartan09** [comment]
Putting the final fix here:
```toml
[jobs.job-name]
command = ["sh", "-c", "cargo run | jq -C --unbuffered"]
kill = ["pkill", "-TERM", "-P"]
```

**Comment by dev0T** [comment]
For anyone looking for the solution with bunyan:

```toml
[jobs.run-long]
command = [
    "sh", "-c", "cargo run | bunyan --color"
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
kill = ["pkill", "-TERM", "-P"]
```
