### ISSUE TITLE
Hangs on "computing..." when fixing an error

### ISSUE THREAD

**Issue by Smona** [Canop/bacon#349]
I have a very basic axum server that i'm running with bacon. it mostly works with the following config, but when i trigger a simple mismatched type compiler error, and then fix it, bacon will get stuck "computing...", and the error won't go away. if i hit F5 then it recovers.

```toml
[jobs.run]
command = ["cargo", "run", "--color", "always"]
need_stdout = true
allow_warnings = true
on_change_strategy = "kill_then_restart"
```

I'm on bacon 3.12.0
