### ISSUE TITLE
`kill` command does not seem to run during `kill_then_restart`

### ISSUE THREAD

**Issue by ytham** [Canop/bacon#351]
We're running into an issue when running our `axum` web server with bacon (ran via `bacon axum-server`). We have the `on_change_strategy` set to `"kill_then_restart"`, but after a change, the restart happens but the server is not killed (thus there is contention on the port until we manually kill the previous process).

Reproducibility: 100%
Version: bacon 3.12.0

bacon.toml:

```toml
[jobs.axum-server]
command = [
  "cargo",
  "test",
  "--package",
  "server",
  "--lib",
  "--",
  "tests::run_axum_server",
  "--ignored",
  "--exact",
  "--show-output",
  "--nocapture",
]
watch = ["src", "tests", "Cargo.toml", "Cargo.lock"]
env = { "RUST_LOG" = "info" }
background = false
need_stdout = true
on_change_strategy = "kill_then_restart"
kill = ["pkill", "-2", "-f", "cargo test"]

[settings]
default_job = "axum-server"
```

**Comment by c-git** [comment]
I noticed you have a custom `kill` value. Did you already try the one from here https://dystroy.org/bacon/cookbook/#long-running-programs

**Comment by ytham** [comment]
I did; that also did not work (which is why I had to try the custom `kill` value)

**Comment by c-git** [comment]
Is the project you're working on public? I wouldn't mind trying to reproduce it and see if I can figure it out.

**Comment by ytham** [comment]
unfortunately not at the moment, but I can try to make a minimal reproduction repo when I have a minute

**Comment by c-git** [comment]
Sure, just ping me once it's ready. I don't use axum but it works for me with local shuttle runs and scripts.

**Comment by c-git** [comment]
Two things. 

1. How do you normally kill it to continue testing?
2. If you want to set the default job put `default_job = "axum-server"` at the top of the file at the top level. It doesn't seem to be working where it is right now.

**Comment by ytham** [comment]
1. Normally I kill it via:

```bash
sudo lsof -i :3030  # PID of the app using the port
kill -2 <PID>
```

2. Ah thanks!

**Comment by c-git** [comment]
@Canop I realized there are two different kill commands. The one I've been using is not the one I pointed to yesterday. I tried the one I pointed to yesterday and that didn't work. The one used [here](https://dystroy.org/bacon/cookbook/#bacon-cli-snippets) did work but I didn't realize it wasn't documented anywhere else.

@ytham Thanks for the command. For me the command doesn't have `cargo test` in it so I'm thinking that might be why your kill command doesn't work.

I ran it in a GitHub codespace and what I see is

```
@c-git ➜ /workspaces/bacon-repro (main) $ ps
    PID TTY          TIME CMD
   9804 pts/0    00:00:00 bash
  48811 pts/0    00:00:00 test_server-980
  49256 pts/0    00:00:00 ps
@c-git ➜ /workspaces/bacon-repro (main) $ 
```

So the command that worked for me to kill it was `pkill "test_server"`

See below for the config that did work for me.

```toml
default_job = "axum-server"

[jobs.axum-server]
command = [
  "cargo",
  "test",
  "--package",
  "bacon-repro",
  "--",
  "--show-output",
  "--nocapture",
]
watch = ["src", "tests", "Cargo.toml", "Cargo.lock"]
env = { "RUST_LOG" = "info" }
background = false
need_stdout = true
on_change_strategy = "kill_then_restart"
kill = ["pkill", "-TERM", "-P"]
```
