### ISSUE TITLE
a menu, triggered by a key, allowing to select a job to launch (maybe with a digit key)

### ISSUE THREAD

**Issue by Canop** [Canop/bacon#364]
Discussion started [here](https://github.com/Canop/bacon/pull/358#issuecomment-2927259014) and was pursued at https://miaou.dystroy.org/4683?bacon#17879721

**Comment by c-git** [comment]
I do sometimes go over the 10 jobs so allowing the next 26 to be selected with a letter would be appreciated. I've never personally gone over 36 before so not sure if there is value in trying to handle that case.

**Comment by Canop** [comment]
It's done.

Default binding of the open-jobs-menu key is <kbd>ctrl</kbd>-<kbd>j</kbd>. It opens a menu like this:

![Image](https://github.com/user-attachments/assets/04825f83-2160-494a-b0a6-6131747622a2)

(move with the arrow keys, validate with enter, close menu with escape)

When you don't want all the jobs, or want other actions, you can define your own menu:

```TOML
[keybindings]
alt-j = "open-menu(intro=Project Shortcuts (hit *esc* to cancel):,actions=[job:check-all,job:clippy-all,job:open-doc,export:myexport,open-jobs-menu,quit])"
```

This opens a menu like this:

![Image](https://github.com/user-attachments/assets/8f74d953-3344-46fa-b704-e22142b4e9a9)
