### ISSUE TITLE
Make watch directories configurable

### ISSUE THREAD

**Issue by SafariMonkey** [Canop/bacon#39]
Running `bacon -j check-all` reports errors in the examples, but if examples are changed, `bacon` does not rerun the check. I attempted to solve this in #38, but @Canop suggested that the following would be preferable:

```toml
[jobs.test]
command = ["cargo", "test", "--color", "always"]
need_stdout = true
watch = ["tests"]
```

Therefore, only the directories that the job depends on are watched.

One question I have: should `src` be included implicitly? Or should the user have to specify `"src", "tests"`?
