### ISSUE TITLE
Bacon fails on a workspace with inter-member dependencies on Windows

### ISSUE THREAD

**Issue by jDomantas** [Canop/bacon#59]
Reproduction steps:

1. Create a workspace manifest `./Cargo.toml`:

    ```toml
    [workspace]
    members = [
        "crate-a",
        "crate-b",
    ]
    ```

2. Create two member crates:

    ```
    cargo new --lib crate-a
    cargo new --lib crate-b
    ```

3. Make `crate-b` depend on `crate-a` (in `./crate-b/Cargo.toml`):

    ```toml
    [package]
    name = "crate-b"
    version = "0.1.0"
    edition = "2018"

    [dependencies]
    crate-a = { path = "../crate-a" }
    ```

4. Run `bacon` in workspace root, or in either of the crate directories. It fails with message:

    > Error: \`cargo metadata\` exited with an error: error: package collision in the lockfile: packages crate-a v0.1.0 (... dir1 ...) and crate-a v0.1.0 (... dir2 ...) are different, but only one can be written to lockfile unambiguously

Meanwhile `cargo metadata` and `cargo check` work correctly when ran in any of those 3 directories.

OS: Windows 10
`cargo --version`: `cargo 1.54.0 (5ae8d74b3 2021-06-22)`
`bacon --version`: `bacon 1.2.3`
