### ISSUE TITLE
Apply bacon to other languages and compilation backends ?

### ISSUE THREAD

**Issue by Canop** [Canop/bacon#65]
Some parts of bacon were designed for Rust and are tied to cargo:

* default bacon.toml file
* compiler output parsing
* test output parsing
* documentation
* the use of TOML (which is just totally unknown outside the Rust ecosystem)

That's not much. Bacon could be used for other build chains.

But as I don't currently have a personal need, I'll progress there only if there's some interest.
Comment if you're interested.

**Comment by aragonnetje6** [comment]
so for basic functionality, i think it'd be best to basically have modular, replaceable parsing strategies for different compilers/tools, perhaps even formatters, selectable per job in the TOML file?. personally i'd have a usecase for python's mypy, black, and unittest/pytest, as well as haskell's GHC, so i could get started on those after factoring out the rust-specific logic

**Comment by detly** [comment]
As a note, I think you could add support for [Ninja](https://ninja-build.org/) and get out-of-the-box support for the vast majority of C and C++ projects.

**Comment by Kludex** [comment]
I'm interested in this for Python. I maintain a popular web server https://github.com/encode/uvicorn, and I'd be interested in exploring how it would interact with it.

**Comment by Canop** [comment]
@Kludex  Discussing such interaction might be hard to do in this issue. Maybe come to [Miaou](https://miaou.dystroy.org/3768) ?

**Comment by Canop** [comment]
Another step: https://github.com/Canop/bacon/pull/256

**Comment by Canop** [comment]
Roadmap: https://dystroy.org/blog/bacon-everything-roadmap/

**Comment by tyilo** [comment]
[Biome](https://biomejs.dev/) support would be nice :)

**Comment by Canop** [comment]
@tyilo This looks like a good idea. Can you create a specific issue for a biome analyzer ?

**Comment by Canop** [comment]
@tyilo can you check https://github.com/Canop/bacon/pull/271 ?

**Comment by Canop** [comment]
@tyilo can you check https://github.com/Canop/bacon/pull/273 ?

**Comment by tyilo** [comment]
This blog post should probably be linked here: https://dystroy.org/blog/are-they-bacon-yet/

@Canop maybe add the link to the original issue description?

**Comment by mhedgpeth** [comment]
I would love to see swift support. The swift language itself is very friendly to this process. To try to make your analysis of whether this might be worth it, I'll add some data from my own project:

For linting there's: `swiftlint lint --config .swiftlint.yml --strict` which produces this output:
```
Linting 'AppCommands.swift' (60/61)
Linting 'ContentView.swift' (61/61)
/Users/michaelhedgpeth/code/github.com/hedge-ops/app/apple/PeopleWorkKit/Sources/PeopleWorkKit/Extensions/CareerMatrixExtensions.swift:17:1: error: Line Length Violation: Line should be 120 characters or less; currently it has 122 characters (line_length)
Done linting! Found 1 violation, 1 serious in 61 files.
```
For building there's `swift build` which creates this type of failure output:
```swift
/Users/michaelhedgpeth/code/github.com/hedge-ops/app/apple/PeopleWorkKit/Sources/PeopleWorkKit/Extensions/CareerMatrixExtensions.swift:18:40: error: expected ',' separator
 16 |                     jobs: [
 17 |                         MatrixCategoryJobViewModel(id: "software_engineer_1", name: "Software Engineer I", requirements: [
 18 |                                 JobRequ
    |                                        `- error: expected ',' separator
 19 |                                 irementViewModel(
 20 |                                     id: "implementation",
```
For tests there's `swift test` and I don't have output for that.

You know you're at the root of a swift package if there is a `Package.swift` there.

I rely on bacon at least every minute while I'm developing in rust and really miss it when I have to code something in swift. Thanks for the great tool!

**Comment by Canop** [comment]
@mhedgpeth Not having a mac, I don't plan to dive into Swift myself. Would you like to write the bacon analyzer for swift ? Assuming you know Rust, I can provide some guidance in [the chat](https://miaou.dystroy.org/4683).

**Comment by skull-squadron** [comment]
Just got `bacon` working for a one-of Ruby project using `rspec` and `rubocop`.

<details>

<summary>bacon.toml</summary>

```toml
# This is a configuration file for the bacon tool
#
# Complete help on configuration: https://dystroy.org/bacon/config/
# 
# You may check the current default at
#   https://github.com/Canop/bacon/blob/main/defaults/default-bacon.toml

default_job = 'rspec'
summary = false

[jobs.rspec]
command = ['rspec', '--color', '--tty']
need_stdout = true
workdir = '.'
watch = [
  'exe',
  'lib',
  'spec',
  '.rspec',
  'Gemfile',
  'Gemfile.lock',
  'Rakefile',
  '*.gemspec',
]

[jobs.rubocop]
command = ['rubocop']
need_stdout = true
workdir = '.'
watch = [
  'bin',
  'lib',
  'spec',
  '.rspec',
  'Gemfile',
  'Gemfile.lock',
  'Rakefile',
  '*.gemspec',
]

[keybindings]
c = "job:rubocop"
r = "job:rspec"
a = "no-op"
d = "no-op"
i = "no-op"
n = "no-op"
t = "no-op"
```

</details>

In the "It would be nice™" department, maybe I'm doing something wrong but if `watch =` supported regex globs for file matches/exclusions would be really helpful.
