### ISSUE TITLE
Suggestion: less-like key bindings

### ISSUE THREAD

**Issue by Ploppz** [Canop/bacon#72]
Would be nice if the pager could behave a little more like less. Specifically what I personally miss:
Ctrl+D, Ctrl+U for scrolling (for us tenkeyless people)
`/` for searching text

**Comment by Canop** [comment]
Searching is not implemented (I'm not sure there's a need).

You can easily bind ctrld and ctrl-u for scrolling. Just add this in your bacon.prefs file:

```TOML
[keybindings]
ctrl-u = "scroll-page(-1)"
ctrl-d = "scroll-page(1)"
```
