### ISSUE TITLE
How to set `--nocapture` for cargo test command?

### ISSUE THREAD

**Issue by nfedyashev** [Canop/bacon#99]
I would appreciate a lot a hint on how to configure the test command to add `--nocapture` flag to it?
```
command = ["cargo", "test", "--color", "always"]
```

I've tried all combinations I could think of and still can't make it work.

**Comment by Canop** [comment]
There's no really good solution because without capture the output is just dumped with no relation to the test. There's no way for bacon to know what output goes with what test. That's also why `--nocapture` is barely usable as soon as you have many tests (I prefer to just make the test I need to see to fail with `assert!(false)`.

So the only solution within bacon is to dump everything.
This is what bacon normally does... except when there are warnings or errors.
So, what you want here (I'll admit it's not obvious) is this:

```toml
[jobs.test]
command = ["cargo", "test", "--color", "always", "--", "--nocapture"]
need_stdout = true
watch = ["tests"]
allow_warnings = true
```

![image](https://user-images.githubusercontent.com/617006/210040973-aef5ac5f-d9cd-4dc7-8b02-d28f6bc1dbf0.png)
